### ISSUE TITLE
About demo_test.py

### ISSUE THREAD

**Issue by Lucas-xu** [harryhan618/LaneNet#10]
Hi！Im trying to test a image,(demo_test.py).
Then an error occurs
Traceback (most recent call last):
  File "demo_test.py", line 67, in <module>
    main()
  File "demo_test.py", line 31, in main
    x = transform(img)[0]
  File "C:\Users\xuyun\Desktop\LaneNet-master-20190926\utils\transforms\transforms.py", line 43, in __call__
    sample = t(sample)
  File "C:\Users\xuyun\Desktop\LaneNet-master-20190926\utils\transforms\transforms.py", line 70, in __call__
    img = sample.get('img')
AttributeError: 'numpy.ndarray' object has no attribute 'get'
Any help would be amazing.

**Comment by harryhan618** [comment]
Hello! This bug has been fixed. The input to a `transform` should be a dict containing `img` and `segLabel`. 
Also, maybe I would update the codebase these days. So please keep updated. Thanks!
